---

elasticsearch_repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
elasticsearch_package: elasticsearch

elasticsearch_data_dir: /usr/share/elasticsearch/data
elasticsearch_cfg_dir: /usr/share/elasticsearch/config
elasticsearch_log_dir: /var/log/elasticsearch

elasticsearch_network_host: localhost
elasticsearch_http_port: 9200

elasticsearch_script_inline: true
elasticsearch_script_indexed: true

elasticsearch_username: elastic
elasticsearch_password: null
