---

- name: Add HAProxy PPA
  apt_repository:
    repo: "{{ haproxy_ppa }}"
  when: haproxy_ppa != ""

- name: Install HAProxy
  apt:
    name: haproxy={{ haproxy_version }}

# The ctmpl files use `{{` and `}}` as Go template start- and end- strings.
# So for Jinja2 rendering we'll use `!` next to the original delimiters.
- name: Copy over all consul-template ctmpl files
  template:
    block_start_string: "{%!"
    block_end_string: "!%}"
    variable_start_string: "{{!"
    variable_end_string : "!}}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "backend.map.ctmpl"
      dest: "{{ consul_template_tmpl_dir }}/backend.map.ctmpl"
      mode: "0644"
    - src: "certs.pem.ctmpl"
      dest: "{{ consul_template_tmpl_dir }}/certs.pem.ctmpl"
      mode: "0644"
    - src: "haproxy.cfg.ctmpl"
      dest: "{{ consul_template_tmpl_dir }}/haproxy.cfg.ctmpl"
      mode: "0644"

- name: Copy over all consul-template config and service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "backend.map.hcl.j2"
      dest: "{{ consul_template_config_dir }}/backend.map.hcl"
      mode: "0644"
    - src: "certs.pem.hcl.j2"
      dest: "{{ consul_template_config_dir }}/certs.pem.hcl"
      mode: "0644"
    - src: "haproxy.cfg.hcl.j2"
      dest: "{{ consul_template_config_dir }}/haproxy.cfg.hcl"
      mode: "0644"
    - src: "consul-template-render.sh"
      dest: "/usr/local/sbin/consul-template-render.sh"
      mode: "0755"
    - src: "consul-template-render.service"
      dest: "/lib/systemd/system/consul-template-render.service"
      mode: "0644"

- name: Enable and start the consul-template-render service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: "consul-template-render"

- import_tasks: maintenance.yml
- import_tasks: exporter.yml
  when: haproxy_exporter_enabled

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Open HTTP and HTTPS port on the firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443
