---

- name: apticron package is installed
  apt:
    name: apticron

- name: apticron is configured
  template:
    src: apticron.conf.j2
    dest: /etc/apticron/apticron.conf
    owner: root
    group: root
    mode: 0644
