---
# Playbook for setting up a HAProxy load balancing server.

- name: Set up load-balancing servers
  hosts: load-balancer
  become: true
  vars:
    caching_resolver_enabled: false
  roles:
    - role: common-server
      tags: 'common-server'

    - role: load-balancer
      tags: 'load-balancer'

    - role: node-exporter
      tags: 'node-exporter'

    - role: unbound
      when: caching_resolver_enabled
      tags: 'unbound'
